fix:incomplete files removed after an unsuccessful neu create
neutralinojs/neutralinojs-cli pull request #168
Opened 2022-06-29 05:31 UTC by Yash-271120

## Description
Now on unsuccessful neu create due to internet connection problem, the created files get deleted

***
### Fixes(#142)

2022-06-29 07:37 UTC, pathange-s commented
A better description could be: Fix: Remove project files in case of failed `neu create` command execution.

2022-06-29 07:38 UTC, pathange-s requested changes

2022-06-29 07:38 UTC, pathange-s commented on src/modules/creator.js
> +                    fs.rmdirSync(`../${binaryName}`, { recursive: true });
Check indentation. should align with `utils.error..`

2022-06-29 09:19 UTC, Yash-271120 commented
@pathange-s I have made necessary changes please check.

2022-06-29 09:39 UTC, pathange-s commented
LGTM.
Btw you could have used `git reset` to undo a commit. Well, let Shalitha approve these changes and workflows run. Then, a merge 🚀

2022-07-09 10:11 UTC, shalithasuranga approved these changes
Looks good.. Thanks :tada:

2022-07-09 10:21 UTC, merged